spring.application.name=demo
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.port=8080

# MySQL database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_jsp?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=9014840907@mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings (optional if you use JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true